version: '3'

services:
  servidor:
    container_name: servidor-portafolio
    working_dir: /app
    # image: node:12.5.0-alpine
    image: node
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    # command: bash -c "npm i && npm run dev"
    command: ["npm", "run", "dev"]

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
  db:
    container_name: db
    image: mariadb:10.3.35-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      # - MYSQL_DATABASE=wordpress
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    expose:
      - 3306
      - 33060
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_CONTROLPASS=0
    links:
      - db:db
  www:
    container_name: api-portafolio
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./docker_config/config_nginx/nginx_www.conf:/etc/nginx/nginx.conf:ro
      - ./backend:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=portafolio-test.test,www.portafolio-test.test
      - LETSENCRYPT_HOST=portafolio-test.test,www.portafolio-test.test
      - LETSENCRYPT_EMAIL=rodrigotarrio2@gmail.com
    depends_on:
      - nginx-proxy
  php:
    build: ./backend/.
    container_name: php-container
    expose:
      - 9000
    volumes:
      - ./backend/:/usr/share/nginx/html/
      - ./docker_config/php-docker-config/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
volumes: 
  certs:
  html:
  vhostd:
  database: